name: Tests

on: 
  push: 
    branches: [ developer ]
  pull_request: 
    branches: [ developer ]

jobs: 
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Run tests
        run: vendor/bin/phpunit