name: Tests

on:
  push:
    branches: [ developer ]
  pull_request:
    branches: [ developer ]

jobs: 
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Request Zoom Credentials
        run: |
          echo "Zoom account: "
          $zoom_account = trim(fgets(STDIN));
          echo "Zoom client: "
          $zoom_client = trim(fgets(STDIN));
          echo "Zoom secret: "
          $zoom_secret = trim(fgets(STDIN));
          echo "Meeting ID: "
          $zoom_meeting_id = trim(fgets(STDIN));
          echo "::set-env name=ZOOM_ACCOUNT::$zoom_account"
          echo "::set-env name=ZOOM_CLIENT::$zoom_client"
          echo "::set-env name=ZOOM_SECRET::$zoom_secret"
          echo "::set-env name=ZOOM_MEETING_ID::$zoom_meeting_id"
      - name: Run tests
        run: vendor/bin/phpunit